source D:/MySQL_Lab/lab01_file/department.sql
source D:/MySQL_Lab/lab01_file/employee.sql
source D:/MySQL_Lab/lab01_file/department_location.sql
source D:/MySQL_Lab/lab01_file/project.sql
source D:/MySQL_Lab/lab01_file/worksOn.sql
source D:/MySQL_Lab/lab01_file/dependents.sql
source D:/MySQL_Lab/lab01_file/load-department.sql
source D:/MySQL_Lab/lab01_file/load-employee.sql
source D:/MySQL_Lab/lab01_file/load-dloc.sql
source D:/MySQL_Lab/lab01_file/load-project.sql
source D:/MySQL_Lab/lab01_file/load-worksOn.sql
source D:/MySQL_Lab/lab01_file/load-dependents.sql
