DROP TABLE IF EXISTS DEPARTMENT_LOCATION RESTRICT;

CREATE TABLE DEPARTMENT_LOCATION(
    Dnumber INTEGER(4) NOT NULL,
    DLocation VARCHAR(25) NOT NULL,
    INDEX (DLocation),
    FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
);