DROP TABLE IF EXISTS WORKS_ON RESTRICT;

CREATE TABLE WORKS_ON (
  Essn CHAR(9) NOT NULL,
  Pno INTEGER(4) NOT NULL,
  Hours DECIMAL(3.1),
  PRIMARY KEY (Essn, Pno),
  FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
  FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
);